from .vsrfi_stream import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_1, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_1
from .vsrfi_frames import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_2, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_2
from . import server as _vsrfi_server  # registers /vsrfi/ API routes

# Merge the mappings from both nodes
NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS_1, **NODE_CLASS_MAPPINGS_2}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS_1, **NODE_DISPLAY_NAME_MAPPINGS_2}

WEB_DIRECTORY = "./web"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
